// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final int kLeftMotor1Port = 15;
    public static final int kLeftMotor2Port = 14;
    public static final int kRightMotor1Port = 12;
    public static final int kRightMotor2Port = 13;
    public static final int kIntakeMotorPort = 0; // To be changed when we have an actual intake
    //PID constants for PIDCommand Setmotor:
    public static final double kp = 6e-5;
    public static final double ki = 0;
    public static final double kd = 0;
    //Slowmotion, deadzone, etc:
    public static final double slowMoFactor = 0.5;
    public static final double DEADZONE = 0.05;
}

