// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

import com.kauailabs.navx.frc.AHRS;
import com.pathplanner.lib.PathConstraints;
import com.pathplanner.lib.PathPlanner;
import com.pathplanner.lib.PathPlannerTrajectory;
import com.pathplanner.lib.commands.FollowPathWithEvents;

import edu.wpi.first.math.trajectory.Trajectory;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.IntakeSubsystem;
import frc.robot.subsystems.TankDriveSubsystem;

// NOTE:  Consider using this command inline, rather than writing a subclass.  For more
// information, see:
// https://docs.wpilib.org/en/stable/docs/software/commandbased/convenience-features.html
public class AutonomousCommand extends CommandBase {
  /** Creates a new AutonomousCommand. */
  private AHRS gyro;
  private TankDriveSubsystem drive;
  private IntakeSubsystem intake;
  private HashMap<String, Command> eventMap;
  List<PathPlannerTrajectory> trajectory;
  
  public AutonomousCommand(AHRS _Gyro, TankDriveSubsystem _drive, IntakeSubsystem _intake, Integer path, HashMap<String, Command> map) {
    
  }
  


}