// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;
import frc.robot.Constants;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.LEDsystem;

public class setLedColor extends CommandBase {
    private final LEDsystem sys;
    private final Constants.color setColor;

    public setLedColor(LEDsystem strips, Constants.color hold) {
        sys = strips;

        setColor = hold;
        addRequirements(sys);
        System.out.println("A");
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        sys.setColor(setColor);
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        // check for if one of the triggers is active
        // sys.setColor(setColor);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        System.out.println("B");
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        System.out.println("C");
        return true;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
